<?php

namespace DoctrineProxies\__CG__\Yummi\Domain\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OrderPizzaSideDishes extends \Yummi\Domain\Entities\OrderPizzaSideDishes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Yummi\\Domain\\Entities\\OrderPizzaSideDishes' . "\0" . 'id', '' . "\0" . 'Yummi\\Domain\\Entities\\OrderPizzaSideDishes' . "\0" . 'sideDishes', '' . "\0" . 'Yummi\\Domain\\Entities\\OrderPizzaSideDishes' . "\0" . 'price', '' . "\0" . 'Yummi\\Domain\\Entities\\OrderPizzaSideDishes' . "\0" . 'order'];
        }

        return ['__isInitialized__', '' . "\0" . 'Yummi\\Domain\\Entities\\OrderPizzaSideDishes' . "\0" . 'id', '' . "\0" . 'Yummi\\Domain\\Entities\\OrderPizzaSideDishes' . "\0" . 'sideDishes', '' . "\0" . 'Yummi\\Domain\\Entities\\OrderPizzaSideDishes' . "\0" . 'price', '' . "\0" . 'Yummi\\Domain\\Entities\\OrderPizzaSideDishes' . "\0" . 'order'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OrderPizzaSideDishes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): string
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSideDish(\Yummi\Domain\Entities\SideDish $sideDish): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSideDish', [$sideDish]);

        parent::setSideDish($sideDish);
    }

    /**
     * {@inheritDoc}
     */
    public function getSideDish(): \Doctrine\Common\Collections\ArrayCollection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSideDish', []);

        return parent::getSideDish();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrder(\Yummi\Domain\Entities\Order $order): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrder', [$order]);

        parent::setOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder(): \Yummi\Domain\Entities\Order
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrder', []);

        return parent::getOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice(\Yummi\Domain\Entities\Price $price): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPizza(): \Yummi\Domain\Entities\Price
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPizza', []);

        return parent::getPizza();
    }

}
